45 i18n remplacer tout le text existant
mbcube/berlin-portal pull request #56
Opened 2022-08-23 13:27 UTC by hebaabbadi

remplacement de tout de text existant dans la page d'acceuil

2022-08-23 14:07 UTC, mbcube requested changes

2022-08-23 14:07 UTC, mbcube commented on pages/index.tsx
> +                    <option value="en">English</option>
faut traduire les langue aussi!! 
par example en francais c'est : 
Francais, Anglais, Allemand

2022-08-23 14:07 UTC, mbcube commented on pages/index.tsx
> +                          {t('a')} <br />
C'est bon pratique d'utiliser des nom plus descriptif. 
Par Example :  t('workStudyTitle')

2022-08-23 14:07 UTC, mbcube commented on pages/index.tsx
> +                        <p className="page-header-ui-text">{t('header')}</p>
C'est bon pratique d'utiliser des nom plus descriptif. 
Par Example :  t('workStudyDescription')

2022-08-23 14:07 UTC, mbcube commented on pages/index.tsx
> +                    <h2> {t('h')}</h2>
C'est bon pratique d'utiliser des nom plus descriptif. 
Par Example :  t('learnHeader')

2022-08-23 14:07 UTC, mbcube commented on pages/index.tsx
>                      Login
faut traduire Login

2022-08-24 13:47 UTC, mouadbouras approved these changes

2022-08-24 15:22 UTC, mouadbouras approved these changes

2022-08-24 15:24 UTC, mbcube approved these changes

2022-08-24 15:24 UTC, merged