the field on the student  and the price they pay, during registratio…
mbcube/berlin-portal pull request #58
Opened 2022-08-27 13:39 UTC by hebaabbadi

…n are done

2022-08-29 20:11 UTC, mbcube requested changes

2022-08-29 20:11 UTC, mbcube commented on components/forms/user-form.tsx
> +            type="text"
type devrais pas etre text, c'est des numero seulement

2022-08-30 10:49 UTC, mbcube requested changes

2022-08-30 10:49 UTC, mbcube commented on components/forms/user-form.tsx
>              {...register('Payment', {
you're registering twice

2022-08-31 10:07 UTC, mbcube requested changes

2022-08-31 10:07 UTC, mbcube commented on pages/users/[userId].tsx
> +        Payment: formData.Payment,
lowercase

2022-08-31 10:07 UTC, mbcube commented on pages/users/[userId].tsx
> +        Payment: formData.Payment,
payment: formData.payment

2022-08-31 10:07 UTC, mbcube commented on pages/users/index.tsx
> +                                      )}
lowercase: user.payment

2022-08-31 10:07 UTC, mbcube commented on pages/users/new.tsx
> +    Payment: null
lowercase:  payment

2022-09-01 20:02 UTC, mbcube requested changes

2022-09-01 20:02 UTC, mbcube commented on pages/users/[userId].tsx
> +        Payment: formData.payment,
`payment : formData.payment`

-.-

2022-09-01 20:02 UTC, mbcube commented on pages/users/new.tsx
> +        formData.Payment
`formData.payment`

-.-

2022-09-01 20:02 UTC, mbcube commented on pages/users/new.tsx
> +      Payment: null,
`payment: null`

-.-

2022-09-04 11:37 UTC, mouadbouras approved these changes

2022-09-04 11:38 UTC, mouadbouras approved these changes

2022-09-04 11:41 UTC, mbcube approved these changes

2022-09-04 11:41 UTC, merged